sudo: required
dist: trusty

notifications:
  email:
    - laszewski@gmail.com
    - kevinwangfg@gmail.com

before_install:
  - echo "- BEFORE INSTALL -----------"
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository -y ppa:fkrull/deadsnakes-python2.7
  - sudo apt-get update
  - echo "-----------------------------"

addons:
  apt:
    packages:
      - python-dev
      - python-simplejson

git:
  submodules: false

virtualenv:
  system_site_packages: true

#os:
#  - linux
#  - osx

language: python

python:
  - "2.7"

install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7
  - sudo apt-get update
  - sudo apt-get upgrade
  # - export PATH="/opt/python/2.7.10/bin:$PATH"
  - echo $PATH
  - sudo pip install --upgrade pip
  - which python
  - python --version
  - pip --version
  - mkdir ~/.cloudmesh
  - sudo pip install pyyaml --upgrade --force
  - sudo pip install lockfile
  - curl -L http://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz | tar xz
  - cd pycrypto-2.6.1
  - python setup.py install
  - cd ..
  - git clone https://github.com/cloudmesh/client.git
  - cd client
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-doc.txt
  - pip install -U -r requirements-test.txt
  - pip install -U .
  - ln -s `pwd` $(dirname `which python`)/../lib/python2.7/site-packages/cloudmesh_client

script:
  - pwd
  - ls
  - cat /home/travis/virtualenv/python2.7_with_system_site_packages/bin/cm
  - cm version
  - pip install nose
  - nosetests -v --nocapture tests/cm_basic
#  -  py.test tests/cm_basic
#  - make doc
#  - cm help

